language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
  - '0.6'
  - 'iojs'
  - 'iojs-v1.0.4'

before_script:
  # Install JSHint
  - npm install -g jshint

deploy:
  provider: openshift
  user: theo.fidry@gmail.com
  password:
      secure: s1rGf2kwXpvcwMBtsDJBN1yaWS/urpwGGWrTdO8MMMkQTYk2vHvFP5/lM26CtYnX8YqYU5dJry4M8v5A+hJ4cUQpOxn2lW1+3/50Rlrf+SqMBxGUP1DR6KyQ32ysQaqICeOP+cFVkjYvh2rmaXzZ6kGNJTomgn+wgbDlsuR8DoE=
  app: amelibis
  domain: tfidry
  on:
    repo: theofidry/amelibis
  deployment_branch: origin/deploy

notifications:
  email:
    - theo.fidry@gmail.com
