language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
  - '0.6'
  - 'iojs'
  - 'iojs-v1.0.4'

before_script:
  # Install StrongLoop
  - npm install -g strongloop
  # Install JSHint
  - npm install -g jshint
  # Install Google JsLint
  - sudo apt-get install python-pip
  - sudo pip install https://closure-linter.googlecode.com/svn/trunk/
after_script:
  - slc build --install --commit
  - git checkout deploy
  - git push origin deploy

branches:
  only:
    - master

deploy:
  provider: openshift
  user: theo.fidry@gmail.com
  password:
      secure: qPque+u0M532dsaSoeOEMyIyFBnBucFGVg1IpYZqagsX+FLWeAbKRqjGf4K6KPz5veuW3OVkykKn6b09oaiuwGskMNsDvTXBram20w23bkmeYXxQ54dTnhSbgsriDsdiVGcBYJ5Ok1fwwBPBstfMTWLqXEddkQwKk4S1VDFov90=
  app: amelibis
  domain: tfidry
  on:
    repo: theofidry/amelibis
  deployment_branch: deploy

notifications:
  email:
    - theo.fidry@gmail.com
