language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
  - '0.6'
  - 'iojs'
  - 'iojs-v1.0.4'

deploy:
  provider: openshift
  user: theo.fidry@gmail.com
  password:
    secure: dUf62DTPLDW/Xl/2NcJ12C12yl4UBa52GlrSgjJ511C3TB0alUJ/+M1ZI3nKqRt6xfRvXWnJ2Qh5P+leTD5TmZfeN5gDzFDkJ6tv3asMl9HsCs5iZUdT93FTVkU0I1eeI/J/S2nzdWIfRy/FRF7Gjg2evRcofMv0VwU1b0IW8cM=
  app: amelibis
  domain: tfidry
  on:
    repo: theofidry/amelibis
  deployment_branch: deploy

notifications:
  email:
    - theo.fidry@gmail.com
